avasus/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('coreapp.urls')),
]

coreapp/urls.py
from django.contrib import admin
from django.urls import path
from coreapp.views import home, login_view, cadastro_view, termos, logout_view, agendar

app_name = "coreapp"

urlpatterns = [
    path('', home, name='home'),
    path('login', login_view, name='login'),
    path('cadastro', cadastro_view, name='cadastro'),
    path('termos de uso', termos, name='termos'),
    path('logout', logout_view, name='logout'),
    path('agendar', agendar, name='agendar'),
]

coreapp/models.py
from django.db import models
from django.contrib.auth.models import User
import xml.etree.ElementTree as ET
import requests
from datetime import  datetime
# Create your models here.
class Estabelecimento(models.Model):
    co_cnes = models.CharField(max_length = 14 )
    nome = models.CharField(max_length = 100)

    def __str__(self):
        return f"{self.nome}, {self.co_cnes}"
    

class Aluno(models.Model):
    xml_url = "https://selecoes.lais.huol.ufrn.br/media/grupos_atendimento.xml"
    response = requests.get(xml_url)
    if response.status_code == 200:
        root = ET.fromstring(response.content)
        grupos = root.findall('.//grupoatendimento')
        opcoes = {}
        
        map = 0
        for grupo in grupos:
            map = map + 1
            opcoes[str(map)] = grupo.find('nome').text
        
    user = models.OneToOneField(User, on_delete=models.PROTECT,)

    nome_completo = models.CharField(max_length = 80 )
    data_de_nascimento = models.DateField()
    grupo_de_atendimento = models.CharField(
        choices = opcoes,
        max_length = 100
    )
    teve_covid_recentemente = models.BooleanField()

    def __str__(self):
        return self.nome_completo
class Agendamento(models.Model):
    estabelecimento = models.ForeignKey(Estabelecimento, on_delete = models.SET_NULL, null  =True)
    aluno = models.ForeignKey(Aluno, on_delete = models.PROTECT, )
    date = models.CharField( verbose_name  = "horário", max_length = 50)
        

coreapp/forms/auth_forms.py
from django import forms
from coreapp.models import Aluno
from datetime import  datetime
from django.contrib.auth.models import User
import xml.etree.ElementTree as ET
import requests
from utils.utils import validate_cpf 
class LoginForm(forms.Form):
    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf').replace('.', '' ).replace('-', '')
       
        if not validate_cpf(cpf):
            raise forms.ValidationError('Formato de cpf incorreto ou inválido')
        elif not User.objects.filter(username = cpf).exists():
            raise forms.ValidationError('Esse cpf não é cadastrado')
        return cpf
        
       
    cpf = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class': 'mask-cpf'
            }
        )
        )
    senha = forms.CharField(
        widget=forms.PasswordInput(),
        
    )
    

class SingUpForm(forms.ModelForm):
    cpf = forms.CharField(
        widget= forms.TextInput(
            attrs={
                'class': 'mask-cpf'
            }
        )
    )
    senha = forms.CharField(
        widget=forms.PasswordInput(),
        
    )
    senha2 = forms.CharField(
        label="confirmação de senha",
        widget=forms.PasswordInput(),
        
    )
    
    data_de_nascimento = forms.DateField(
        widget= forms.TextInput(
            attrs={
                'class': 'mask-date'
            }
        )
    )
    xml_url = "https://selecoes.lais.huol.ufrn.br/media/grupos_atendimento.xml"
    response = requests.get(xml_url)
    if response.status_code == 200:
        root = ET.fromstring(response.content)
        grupos = root.findall('.//grupoatendimento')
        opcoes = {'0':'Escolha uma opção',}
        
        map = 0
        for grupo in grupos:
            map = map + 1
            opcoes[str(map)] = grupo.find('nome').text
        
            
       
    
    teve_covid_recentemente = forms.ChoiceField(
        widget= forms.RadioSelect(
            attrs={
                'class': 'radio-button',
            }
        ),
        label="teve covid nos ultimos 30 dias ?",
        choices=[
            (True,"sim",),
            ( False,"não",)
        ]
    )
    class Meta:
        model =  Aluno
        fields = [
            'nome_completo',
            'data_de_nascimento',
            'grupo_de_atendimento',
            'teve_covid_recentemente',
        ]
    
    """ def clean_teve_covid_recentemente(self):
        resposta = self.cleaned_data.get('teve_covid_recentemente')
        if resposta:
            return resposta
        raise forms.ValidationError("você não pode participar se teve covid recentemente")
     """
    
        
    
    def clean_cpf(self):
        cpf = self.cleaned_data.get('cpf').replace('.', '' ).replace('-', '')
       
        if not validate_cpf(cpf):
            raise forms.ValidationError('Informe um cpf válido')
        elif User.objects.filter(username = cpf).exists():
            raise forms.ValidationError('Um perfil com esse cpf já existe')
        return cpf
    
    def clean_data_de_nascimento(self):
        br_data = self.cleaned_data.get('data_de_nascimento')       
        today = datetime.today()
        born = datetime.strptime(str(br_data), '%Y-%m-%d').date()
        born_year = born.year
        born_day = born.day
        born_month = born.month
        this_year = today.year
        this_month = today.month
        this_day = today.day
        if this_year - born_year >= 1:
            valid =  True
        elif this_year - born_year == 0 and this_month > born_month:
            valid = True
        elif this_year - born_year == 0 and this_month == born_month and this_day >= born_day:
            valid = True
        else:
            valid = False
        if valid:
            return br_data
        else:
            raise forms.ValidationError('está data de nascimento não é possível')
      
        """ 
        if valid:
            return br_data
        else:
            raise forms.ValidationError('você precisa ter mais de 18 anos para criar uma conta')
      """
    
    

    def clean(self):
        cleaned_data = self.cleaned_data
        senha = cleaned_data.get('senha')
        senha2 = cleaned_data.get('senha2')
       
        if senha == senha2:
            
            return cleaned_data
        else:
            raise forms.ValidationError('as senhas precisam ser iguais')
    
                

coreapp/forms/to_schedule_form.py
from typing import Any
from django import forms
from coreapp.models import Agendamento
from datetime import datetime, timedelta, date
import pytz
class ScheduleForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        age = kwargs.pop('age', None)
        super(ScheduleForm, self).__init__(*args, **kwargs)
        self.age = age

        now = datetime.today().isoweekday()
        choices = {'': '---------'}
        if age <= 29:
            horary = '13' 
        elif age <= 39:
            horary = '14'
        elif age <= 49:
            horary = '15'  
        elif age <= 59:
            horary = '16'
        else:
            horary = '17'
        self.horary = horary
        map_day_names = {
            '0': 'quarta-feira',
            '1': 'quinta-feira',
            '2': 'sexta-feira',
            '3': 'sábado',
        }
        time_now =  datetime.now(pytz.timezone('America/Sao_Paulo')).time()
        age_horary =datetime.strptime(f'{self.horary}::00::00', '%H::%M::%S').time() 
        if now == 6 and time_now > age_horary:
            next_date = date.today() + timedelta(days=4)
        elif now == 7:
            next_date = date.today() + timedelta(days=3)
        else:
            next_date = date.today() + timedelta(days=3 - now)
        for i in range(4):
            choices[str(next_date.strftime("%d/%m/%Y"))] = f'{map_day_names[str(i)]}, dia {next_date.strftime("%d/%m/%Y")} às {horary}:00 horas '
            next_date = next_date + timedelta(days=1)
        
        
        self.fields['date'] = forms.ChoiceField(
            label="Data",
            choices=choices,
        )

    class Meta:
        model = Agendamento
        fields = [
            "estabelecimento",
            "date",
        ]
    def clean(self):
        cleaned_data = self.cleaned_data
        estabelecimento = cleaned_data.get('estabelecimento')
        date = f"{cleaned_data.get('date')} às {self.horary}:00"
        
        
        agendamentos = Agendamento.objects.filter(estabelecimento = estabelecimento, date = date)
        if agendamentos.count() > 4:
            raise forms.ValidationError("Desculpe, mas esse horário já está totalmente ocupado")
        
        
        return cleaned_data
    

    def clean_date(self):
        data = self.cleaned_data["date"]
        age_horary =datetime.strptime(f'{self.horary}::00::00', '%H::%M::%S').time() 
        date_horary = datetime.strptime(data, '%d/%m/%Y').date()
        time_now =  datetime.now(pytz.timezone('America/Sao_Paulo')).time()
        
        today = date.today()
        
        if(today > date_horary ):
            raise forms.ValidationError("essa data já passou, escolha um horário futuro")
        elif today == date_horary:
            if time_now > age_horary:
                raise forms.ValidationError("Este horário não está mais disponível")
        return data
    

coreapp/views.py
from django.shortcuts import render, redirect
from coreapp.forms import LoginForm, SingUpForm, ScheduleForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth import authenticate, login, logout
from coreapp.models import Aluno, Agendamento
from django.contrib.auth.models import User
from django.contrib import messages
from utils.utils import verify_age_is_more_than_18, verify_age
from datetime import  datetime, date
import pytz
@login_required(login_url="coreapp:home")
def agendar(request):
    user_data = Aluno.objects.get(user = request.user)
    agendamentos = Agendamento.objects.filter(aluno = user_data)
    today = datetime.today()
    born = user_data.data_de_nascimento
    idade = verify_age(born,today)
    if idade <= 29:
        horary = '13' 
    elif idade <= 39:
        horary = '14'
    elif idade <= 49:
        horary = '15'  
    elif idade <= 59:
        horary = '16'
    else:
        horary = '17'
    age_horary =datetime.strptime(f'{horary}::00::00', '%H::%M::%S').time()
    no_expireds = 0
    if agendamentos:
        today = date.today()
        for agendamento in agendamentos:
            data = agendamento.date[:10]
            date_day = datetime.strptime(data, '%d/%m/%Y').date()
            if today < date_day:
                no_expireds = 1
                break
            elif today == date_day:
                time_now =  datetime.now(pytz.timezone('America/Sao_Paulo')).time()
                if age_horary > time_now:
                    no_expireds = 1
                    break
    if no_expireds != 0:
        return redirect("coreapp:home")
    if not request.user.is_superuser:
        
        
        if idade < 18 or user_data.grupo_de_atendimento == "67" or user_data.grupo_de_atendimento == "70" or user_data.grupo_de_atendimento == "65" or user_data.teve_covid_recentemente:
            return redirect('coreapp:home')
        
        if request.method == 'POST':
            form = ScheduleForm(data=request.POST, age = idade)
            if form.is_valid():
                data = form.save(commit = False)
                date_day = form.cleaned_data.get("date")
                
                data.date_day = f"{date_day} às {horary}:00"
                data.aluno = Aluno.objects.get(user=request.user)
                data.save()
                messages.add_message(request, messages.SUCCESS, "Seu agendamento foi realizado com sucesso")
                return redirect("coreapp:home")
        else:
            form = ScheduleForm(age = idade)
    else:
        return render(request, 'coreapp/authentication_screen.html')
    
    context = {
        'form' : form,
        'form_action': '/agendar',
        'page': 'agendar exame'
    }
    return render( request, 'coreapp/form_screen.html',context)

def home(request):
    ...
    if request.user.is_authenticated and not request.user.is_superuser:
        
        ...
        user_data = Aluno.objects.get(user = request.user)
        today = datetime.today()
        born = user_data.data_de_nascimento
        if born is not None:
            esta_apto = True
            idade = verify_age(born,today)
            if idade < 18 or user_data.grupo_de_atendimento == "67" or user_data.grupo_de_atendimento == "70" or user_data.grupo_de_atendimento == "65" or user_data.teve_covid_recentemente:
                esta_apto = False
            
            context = {
                'user_data' : user_data,
                'idade' : idade,
                'esta_apto': esta_apto,
            }
        else:
            context = {
                'user_data' : user_data,
            }

        return render(request,'coreapp/home.html',context)
    else:
        return render(request, 'coreapp/authentication_screen.html')

def login_view(request):
    if request.user.is_authenticated and not request.user.is_superuser:
        return redirect("coreapp:home")

    if request.method == 'POST':
        
        form = LoginForm(data= request.POST)
        if form.is_valid():
            user = authenticate(
                request,
                username = form.cleaned_data.get('cpf'),
                password = form.cleaned_data.get('senha')    
            )
            if user is not None:
                login(request, user)

                return redirect("coreapp:home")


    else:
        form = LoginForm()
    context = {
        'form': form,
        'form_action': '/login',
        'page': 'Login' 
    }
    return render(request, 'coreapp/form_screen.html',context)

def cadastro_view(request):
    if request.user.is_authenticated:
        return redirect("coreapp:home")

    if request.method == 'POST':
        form = SingUpForm(data = request.POST)  
        if form.is_valid():     
            data = form.save(commit = False)
            cpf = form.cleaned_data.get('cpf')
            senha = form.cleaned_data.get('senha')
            user = User.objects.create_user(username=cpf,password=senha)
            user.save()
            data.user = user
            data.save()
            messages.add_message(request, messages.SUCCESS, "Seu Perfil foi criado com sucesso")
            today = datetime.today()
            br_data = form.cleaned_data.get('data_de_nascimento')
            born = datetime.strptime(str(br_data), '%Y-%m-%d').date()
            request.session['born'] = str(born)
            e_de_maior =verify_age_is_more_than_18(born,today)

            text = "você não está apto para a pesquisa pois:"
            if not e_de_maior:
                text = text + "Não tem 18 anos ou mais;"
            condition = form.cleaned_data.get('teve_covid_recentemente') == "True"
            if condition:
                text = text + " Teve covid recentemente;"
            if form.cleaned_data.get('grupo_de_atendimento') == "67" or form.cleaned_data.get('grupo_de_atendimento') == "70" or form.cleaned_data.get('grupo_de_atendimento') == "65":
                text = text + "É pertencente ao grupo " + form.opcoes[form.cleaned_data.get('grupo_de_atendimento')] + "."
            if text != "você não está apto para a pesquisa pois:":
                messages.add_message(request, messages.WARNING, text)
            return redirect('coreapp:login')
           
    else:
        form = SingUpForm()
    context = {
        'form': form,
        'form_action': '/cadastro',
        'page': 'Cadastro'

    }
    return render(request, 'coreapp/form_screen.html',context)

def termos(request):
    return render(request,"coreapp/termos.html", )

@login_required
def logout_view(request):
    logout(request)
    return redirect('coreapp:home')

coreapp/templates/coreapp/authentication_screen.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>autenticação</title>
    <link rel="stylesheet" href={% static "coreapp/css/style.css" %}>
</head>
<body>
    <center>
        <div>
            <h1>Já possue uma conta ?</h1>
           
            <a href={% url "coreapp:login" %}>
                <button class="button-green">
                    Entrar
                </button>
            </a>
           
            <h1>Ou</h1>
           
            <a href={% url "coreapp:cadastro" %}>
                <button class="button-green">
                    cadastre-se
                </button>
            </a>
            
           </div>
    </center>
  
</body>
</html>

coreapp/templates/coreapp/form_screen.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "coreapp/css/style.css" %}>
    <title>{{page}} </title>
</head>
<body>
    {% if messages %}
        {% for message in messages %}
        <center>
          <div style = "width:50%">
            <div  {% if message.tags == 'warning' %}class="message message-warning" {% else %}class="message message-success"{% endif %} >
              {{ message }}
            </div>
          </div>
        </center>
          
        {% endfor %}
    {% endif %}
    <center>
        <h1 >
           {{page}}
        </h1>
    </center>
   <center>
    <div class= 'card'>
        <div class="main-content container">
            <form action="{{ form_action }}" method="POST">
              {% csrf_token %}
          
              <div class="form-content form-content-grid">
                {% for field in form %}
                  <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{field}}
          
                    {% if field.help_text %}
                      <p class="help-text">{{ field.help_text }}</p>
                    {% endif %}
          
                    {{ field.errors }}
                  </div>
                {% endfor %}
              </div>
              {% if form.non_field_errors %}
              {{form.non_field_errors}}
              {% endif %}
              {% if form.errors %}
              <div class="form-content form-content-grid">
                <div class="form-group">
                  <div class="message message-error">
                    O formulário contém erros
                  </div>
                </div>
              </div>
              {% endif %}
              
              
                
              <center>
                <div class="form-content form-content-grid">
                    <div class="form-group">
                      <button type="submit">{% if form_action == "/login" %}
                        entrar
                    {% else %}
                        enviar
                    {% endif %}</button>
                    </div>
                  </div>
              </center>
            </form>
          </div>
       </div>
   </center>
    
<script src ={% static "coreapp/js/jquery.min.js" %} ></script>
<script src ={% static "coreapp/js/jquery.mask.min.js" %} ></script>
<script src ={% static "coreapp/js/mask.js" %} ></script>
</body>
</html>

coreapp/templates/coreapp/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={% static "coreapp/css/style.css" %}>
    <title>página inicial</title>
    
</head>
<body >
    <header class="main-header-container">
       
        <div class="main-header container">
            
            <h1>
                <center>
                    <span class = "home-title" >revela</span>
                </center>
            </h1>


        </div>
    </header>
    <p style="position: absolute; top: 0; right: 0; text-align: right; margin: 1%;">
        <a style = "color:white" href={% url "coreapp:logout" %}>encerrar seção</a>
    </p>
   <center>
    <div class = "card" style = "margin:2%;">
        <p style = "margin:1%;">Nome: {{user_data.nome_completo}} </p>
        <p style = "margin:1%;">Data de nascimento: {{user_data.data_de_nascimento}}, {{idade}} anos</p>
        <p style = "margin:1%;">Cpf: {{user_data.user}} </p>
        <p style = "margin:1%;">{% if esta_apto %}Você pode participar da pesquisa. ✔{% else %}você não pode participar da pesquisa ❌{% endif %} </p>
        
    </div>
   </center>
   
   {% if  esta_apto %}<center>
    <a href={% url "coreapp:agendar" %}>
        <div class="form-content form-content-grid">
            <div class="form-group">
                <button type="submit">
                   realizar agendamento
                </button>
            </div>
        </div>
    </a>
    
  </center>{% endif %}
   
    
</body>
</html>

coreapp/templates/coreapp/termos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Termos de Uso - </title>
    <style>
        body {
            font-family: Arial, sans-serif;
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
        }
        #container {
            display: flex;
            max-width: 800px;
            width: 100%;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
            overflow: hidden;
            background-color: #fff;
        }
        #content {
            flex-grow: 1;
            padding: 20px;
        }
        #divider {
            width: 1px;
            background-color: #ccc;
        }
        h1, h2 {
            color: #333;
        }
    </style>
</head>
<body>

    <div id="container">
        <div id="content">
            <h1>Termos de Uso</h1>

            <p>Bem-vindo. Estes Termos de Uso regem o uso dos serviços oferecidos por . Ao acessar ou utilizar nossos serviços, você concorda com estes Termos. Leia-os cuidadosamente antes de prosseguir.</p>

            <h2>1. Aceitação dos Termos</h2>
            <p>Ao utilizar nossos serviços, você concorda com todos os Termos apresentados aqui. Se não concordar com algum deles, pedimos que não utilize nossos serviços.</p>

            {
                conteudo ...
            }

            <h2>9. Contato</h2>
            <p>Se tiver dúvidas ou preocupações sobre estes Termos, entre em contato conosco em <a href="">contato@email</a>.</p>

            <p>Agradecemos por escolher !</p>

            <p></p>
            <p>Data de última atualização: 01/01</p>
        </div>
        <div id="divider"></div>
    </div>

</body>
</html>